version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Git installation
          command: apt-get -qq update; apt-get -y install git
      - run:
          name: Latex installation
          command: apt-get -qq update && apt-get install -y --no-install-recommends latexmk texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-luatex texlive-xetex texlive-pictures texlive-lang-french lmodern fonts-font-awesome
      - add_ssh_keys
      - checkout
      - run:
          name: Build th PDF
          command: cd default && latexmk -cd -f -lualatex -interaction=nonstopmode -pdf cv.tex
      - store_artifacts:
          path: ~/project/default/cv.pdf
